---
#- name: Installing required components for automation
#- hosts: vm751cb
- hosts: "{{ host }}"
  roles:
    - no_shutdown_prompt
    - WSManCredSSP
    - winupdate_service_stop_disable
    - no_auto_tray
    - server_manager_golbal
    - server_manager_user
    - reset_computer_password_service
    - target_dir
    - copy_sources
    - chocolatey_install
    - install_python
    - update_path
    - reboot_server
    - copy_file
    - install_freesshd
      #    - install_visual_cpp_build_tools
      #    - install_winbuildtools2019  
    - install_visualstudio2019_buildtools  
    - pip_and_cryptography_update  
    - reboot_server
