---
#- name: Installing required components for automation
- hosts: "{{ host }}"
  gather_facts: no
  roles:
    - chocolatey_install
    - install_visual_cpp_build_tools 
    - reboot_server
    - winupdate_service_stop_disable  
