---
#- name: Installing required components for automation
#- hosts: "{{ host }}"
- hosts: all
  gather_facts: no
  roles:
    - local-admin-enable
    - java-admin_user
    - reset_computer_password_service
    - winupdate_service_start
    - k.windows_updates
    - winupdate_service_stop_disable
    - reboot_server
    #- server_password_finder
    #- memory_password_finder
    #- trace_password_finder
    #- pie_password_finder
    #- java_installer_upload
    #- install_jdk
    #- install_winbuildtools2019  
    #- sso_server_client
    #- sso_tomcat_webapp
    - local-admin-enable
    - install_visualstudio2019_buildtools  
    - no_shutdown_prompt
      #- winupdate_service_stop_disable
    - no_auto_tray
    - winupdate_service_start
    - k.windows_updates
    - winupdate_service_stop_disable
    - reboot_server
    # - server_manager_golbal
    # - server_manager_user
    # - reset_computer_password_service
    # - target_dir
    # - copy_sources
    # - vm_horizon_upload
    - chocolatey_install
    - install_python
    - update_path
    # - reboot_server
    - copy_file
    - pip_and_cryptography_update  
    - install_freesshd              # temporary disabled
    - install_notepadplusplus
#    - install_googlechrome
      #  - install_visual_cpp_build_tools  # temporary disabled
    - net_svc
    - cortana_disable
    #- procdump_enable
    - accept_eula_reg
    #- vm_horizon_upload
    # - vm_broker_upload
    # - vmware_powercli_install
    # - vm_hv_helper_copy
    # - vmbroker_shell_1
    - reboot_server
    - winupdate_service_stop_disable  
    - desktop_ini_file_attr  
    # - vmbroker_shell_2
    # - reboot_server
  #  - install_rds
