---
#- name: Installing required components for automation
- hosts: vm76a
  roles:
    - reboot_server
    - no_shutdown_prompt
    - winupdate_service_stop_disable
    - no_auto_tray
    - server_manager_golbal
    - server_manager_user
    - reset_computer_password_service
    - target_dir
    - copy_sources
    - install_python
 #   - update_path
    - reboot_server
    - copy_file
    - install_freesshd
#    - install_rds
