---
#- name: Installing required components for automation
- hosts: "{{ host }}"
  gather_facts: no
  roles:
    # - reboot_server
    #    - java-admin_user
    #- server_password_finder
    #- memory_password_finder
    #- trace_password_finder
    #- pie_password_finder
    - java_installer_upload
    - install_jdk
    #- sso_server_client
    #- sso_tomcat_webapp
    - no_shutdown_prompt
    - winupdate_service_stop_disable
    - no_auto_tray
    - server_manager_golbal
    - server_manager_user
    # - reset_computer_password_service
    # - target_dir
    # - copy_sources
    # - vm_horizon_upload
    - chocolatey_install
    - install_python
    - update_path
    # - reboot_server
    - copy_file
    - install_freesshd
    - install_notepadplusplus
    - install_googlechrome
    - net_svc
    - cortana_disable
    #- procdump_enable
    - accept_eula_reg
    #- vm_horizon_upload
    # - vm_broker_upload
    # - vmware_powercli_install
    # - vm_hv_helper_copy
    # - vmbroker_shell_1
    - reboot_server
      #- winupdate_service_stop_disable  
    # - vmbroker_shell_2
    # - reboot_server
  #  - install_rds
