---
# tasks file for no_shutdown_prompt
- name: Disable Display Shutdown Event Tracker
  win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows NT\Reliability
    name: ShutdownReasonOn
    data: 0
    type: dword
