---
# tasks file for cortana_disable
- name: Disable Cortana
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
    name: AllowCortana
    data: 0
    type: dword

- name: Disable Cortana Above Lock
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
    name: AllowCortanaAboveLock
    data: 0
    type: dword
