---
# tasks  to disable Windows10 auto update
- name: Disable Windows10 Auto Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword

