---
# tasks file for no_privacy_screen_popup
- name: NoPrivacyScreenPopUp registry setting
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OOBE
    name: DisablePrivacyExperience
    data: 1
    type: dword
