---
# tasks  to disable save password prompt in Edge and Chrome browsers
- name: Disable save password prompt in MS Edge browser
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Edge
    name: PasswordManagerEnabled
    data: 0
    type: dword

- name: Disable save password prompt in Chrome browser
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Google\Chrome
    name: PasswordManagerEnabled
    data: 0
    type: dword
