---
# tasks file for disable_privacy_settings_experience
- name: Disable Display Shutdown Event Tracker
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OOBE
    name: DisablePrivacyExperience
    data: 1
    type: dword
