---
# tasks file for vmbroker_shell_commands
- name: run a multiple vmbroker shell commands
  win_shell: |
    'dir "C:\Program Files\WindowsPowerShell\Modules\VMware.Hv.Helper\" | Unblock-File'
    Set-ExecutionPolicy RemoteSigned
    Enable-PSRemoting -Force
    Set-Item wsman:\localhost\client\trustedhosts * -Force
    Restart-Service WinRM
    Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -confirm:$false