---
# tasks file for zeus_rpc_service
- name: Copy Zeus RPC Service installation files to "C:\Temp\zeus_rpc" directory
  win_copy:
      src: files/zeus_rpc_service/
      dest: C:\Temp\zeus_rpc\

#- name:  Run PIP install
#  win_command: pip install zeus_rpc_service-0.0.dev1-py3-none-any.whl
#    args:
#      chdir:  'C:\Temp\zeus_rpc\'


- name: Run PIP install zeus_utils 1 of 8.
  win_shell: pip install zeus_utils-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_win32_utils 2 of 8.
  win_shell: pip install zeus_win32_utils-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_reg 3 of 8.
  win_shell: pip install zeus_reg-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_msi 4 of 8.
  win_shell: pip install zeus_msi-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_ip_helper 5 of 8.
  win_shell: pip install zeus_ip_helper-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_file_service 6 of 8.
  win_shell: pip install zeus_file_service-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_drive_service 7 of 8.
  win_shell: pip install zeus_drive_service-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd

- name: Run PIP install zeus_rpc_service 8 of 8.
  win_shell: pip install zeus_rpc_service-0.0.dev1-py3-none-any.whl
  args:
    chdir: C:\Temp\zeus_rpc\
    executable: cmd
