---
# tasks file for chocolatey_install
- name: install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled
