---
# tasks file for install_freesshd
- name: Install FreeSSHd
  win_chocolatey:
    name: freeSSHD
    version: 1.3.1

- name: Check if FreeSSHd .ini file exists
  win_stat:
     path: 'C:\Program Files (x86)\freeSSHd\FreeSSHDService.ini'
  register: stat_result

- name: Backup freeSSHD ini file
  win_copy:
    src: 'C:\Program Files (x86)\freeSSHd\FreeSSHDService.ini'
    dest: 'C:\Program Files (x86)\freeSSHd\FreeSSHDService.ini.bak'
    remote_src: yes
  when: stat_result.stat.exists == True

- name: Delete default "FreeSSHDService.ini" file
  win_file:
    path: 'C:\Program Files (x86)\freeSSHd\FreeSSHDService.ini'
    state: absent

- name: Upload custom "FreeSSHDService.ini" file
  win_copy:
    src: files/FreeSSHDService.ini
    dest: 'C:\Program Files (x86)\freeSSHd\'
