---
# tasks file add PORSCHE\ATFGroup to local RDP users
- name: List members of the local "Remote Desktop Users" group
  win_command: powershell.exe -
  args:
    stdin: Get-LocalGroupMember -Name "Remote Desktop Users"


- name: Add PORSCHE\ATFGroup to local RDP users
  ignore_errors: True
  win_command: powershell.exe -
  args:
    stdin: Add-LocalGroupMember -Group "Remote Desktop Users" -Member "PORSCHE\ATFGroup"     


- name: List members of the local "Remote Desktop Users" group
  win_command: powershell.exe -
  args:
    stdin: Get-LocalGroupMember -Name "Remote Desktop Users"

