---
# tasks file for join_domain
- name: Join Domain
  win_domain_membership:
    dns_domain_name: '{{dns_domain_name}}'
    hostname: '{{domain_hostname}}'
    domain_admin_user: '{{win_domain_admin_user}}'
    domain_admin_password: '{{win_domain_admin_password}}'
    state: domain
  register: domain_state

- reboot: Reboot if required
  when: domain_state.reboot_required
